# Generated by Django 3.2.8 on 2021-10-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_GROUP', models.IntegerField()),
                ('ADMIN', models.BooleanField(default=False)),
            ],
        ),
    ]
