# Generated by Django 3.2.8 on 2021-10-20 19:34

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BgHexagone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BG_COLOR', models.CharField(default='#FFFFFF', max_length=7)),
                ('BD_COLOR', models.CharField(default='#000000', max_length=7)),
                ('PATH_FILE', models.FilePathField(path=pathlib.PurePosixPath('/home/neonor/eclipse-workspace/rpgmaster/cartemaker/imgs/bg'))),
                ('PATH_HEXA', models.FilePathField(path=pathlib.PurePosixPath('/home/neonor/eclipse-workspace/rpgmaster'))),
            ],
        ),
        migrations.CreateModel(
            name='Hexagone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
                ('SIZE', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HexaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IcoHexagone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATH_FILE', models.FilePathField(path=pathlib.PurePosixPath('/home/neonor/eclipse-workspace/rpgmaster'))),
                ('PATH_HEXA', models.FilePathField(path=pathlib.PurePosixPath('/home/neonor/eclipse-workspace/rpgmaster'))),
            ],
        ),
        migrations.CreateModel(
            name='ImgHexagone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATH_FILE', models.FilePathField(path=pathlib.PurePosixPath('/home/neonor/eclipse-workspace/rpgmaster'))),
                ('PATH_HEXA', models.FilePathField(path=pathlib.PurePosixPath('/home/neonor/eclipse-workspace/rpgmaster'))),
            ],
        ),
        migrations.CreateModel(
            name='SelectIco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POSITION', models.IntegerField()),
                ('ENABLE', models.BooleanField(default=True)),
            ],
        ),
    ]
