# Generated by Django 3.2.8 on 2021-10-12 08:44

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hexagone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BG_COLOR', models.CharField(default='#000000FF', max_length=9)),
                ('BD_COLOR', models.CharField(default='#00000000', max_length=9)),
                ('PATH_FILE', models.FilePathField(path=pathlib.PurePosixPath('/home/neonor/eclipse-workspace/rpgmaster'))),
                ('PATH_HEXA', models.FilePathField(path=pathlib.PurePosixPath('/home/neonor/eclipse-workspace/rpgmaster'))),
            ],
        ),
    ]
