# Generated by Django 3.2.8 on 2021-10-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartemaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexagone',
            name='BD_COLOR',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='hexagone',
            name='BG_COLOR',
            field=models.CharField(default='000000FF', max_length=8),
        ),
    ]
